title: Title of your CV site
profile_img: assets/img/profilenew.webp
icon_img: assets/img/icon.webp

name: "Mazal Faraj"
job: "〈MSc Student | WIS〉"

phone_number: 07777777777
address: Rehovot, Israel
email: email@example.com
linkedin_username: linkedin
github_username: github
instagram_username: instagram
twitter_username: twitter
facebook_username: facebook
youtube_username: youtube
blog_url: homepage-url

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
