title: "Mazal Faraj"
description: "A personal web page"
cover_image: '/img/IMG_4420.jpg'

plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole

include:
  - README.md  # If you want to make sure README.md is processed
